### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Nuginity** [animegasan/luci-app-speedtest#2]
Saya menggunakan versi 1.3, namun selalu mendapatkan output SyntaxError: Unexpected end of JSON input

**Comment by animegasan** [comment]
> Saya menggunakan versi 1.3, namun selalu mendapatkan output SyntaxError: Unexpected end of JSON input

Bisa di perlihatkan bagaimana output pada terminal jika menjalankan speedtest?

**Comment by Nuginity** [comment]
> > Saya menggunakan versi 1.3, namun selalu mendapatkan output SyntaxError: Unexpected end of JSON input
> 
> Bisa di perlihatkan bagaimana output pada terminal jika menjalankan speedtest?

![Screenshot (291)](https://github.com/animegasan/luci-app-speedtest/assets/63849044/c3d76826-cba7-4b9a-9044-e734357cab93)

**Comment by Nuginity** [comment]
Issue closed. Jika menggunakan tun openclash disarankan mematikan redirect local dns settings dan disable dnsmasq cache

**Comment by animegasan** [comment]
Terima kasih @Nuginity atas reportnya... 

Kedepannya saya akan membuat dokumentasi beberapa masalah. Thanks !
