### ISSUE TITLE
Feature request: Automatic periodic speedtests

### ISSUE THREAD

**Issue by Cypher01** [animegasan/luci-app-speedtest#3]
Great app, exactly what I was looking for, thx!

Can you add a functionality to automatically run periodic speedtests, e.g. every hour?

I already tried to add speedtestcpp to the scheduled tasks, but the results are not visible on LuCI, because you parse and write /etc/speedtest_result by yourself.

Alternatively, you could change your implementation to not parse a result and add the re-formatted line to /etc/speedtest_result, but instead write the raw JSON response of speedtestcpp to the file and parse it on demand for LuCI.

**Comment by animegasan** [comment]
> Great app, exactly what I was looking for, thx!
> 
> Can you add a functionality to automatically run periodic speedtests, e.g. every hour?
> 
> I already tried to add speedtestcpp to the scheduled tasks, but the results are not visible on LuCI, because you parse and write /etc/speedtest_result by yourself.
> 
> Alternatively, you could change your implementation to not parse a result and add the re-formatted line to /etc/speedtest_result, but instead write the raw JSON response of speedtestcpp to the file and parse it on demand for LuCI.

The reason I save the results in the file "/etc/speedtest_result" is because it will make monitoring easier on the Results page.

If you want to add a schedule, I can add it in the next update.

Maybe I will create a settings page for the speedtest schedule. Any suggestions for how the settings page should be created?

BTW, Thanks for the ideas and suggestions!

**Comment by animegasan** [comment]
@Cypher01 
![image](https://github.com/user-attachments/assets/87935015-23c4-4dcb-be02-a57be1fcf785)

Is it good if it is like this?

**Comment by Cypher01** [comment]
Awesome! I will test it soon. Thx!
